// waltz-ng/client/common/svelte/DatePicker.svelte

<script>
    import Flatpickr from 'svelte-flatpickr';
    import 'flatpickr/dist/themes/confetti.css';
    import Icon from "./Icon.svelte";
    import {createEventDispatcher} from "svelte";
    import {timeFormat} from "d3-time-format";

    export let origDate = new Date();
    export let options = {};
    export let canEdit = false;

    const format = timeFormat("%Y-%m-%d");
    const dispatch = createEventDispatcher();


    function handleSubmit(value) {
        if (originalDate.getTime() !== value.getTime()) {
            dispatch("change", value);
        }
    }
    const defaultOptions = {
        dateFormat: "Y-m-d",
        enableTime: false,
        allowInput: true,
        onChange: (d) => {
            handleSubmit(d[0]);
            mode=Modes.VIEW;
        }
    };

    const Modes = {
        VIEW: "VIEW",
        EDIT: "EDIT"
    };


    let mode = Modes.VIEW;
    let originalDate = new Date(origDate);
    let value = new Date(originalDate);


    function onCancel() {
        value = new Date(originalDate);
        mode = Modes.VIEW;
    }

    function onEdit() {
        mode = Modes.EDIT;
    }

    $: mergedOptions = Object.assign({}, defaultOptions, options);
    $: formattedValue = format(value);

</script>

<main>
    {#if mode === Modes.VIEW}
        {formattedValue}
        {#if canEdit}
            <button class="btn-link"
                    on:click={onEdit}>
                <Icon name="edit"/>
                Edit
            </button>
        {/if}
    {:else if mode === Modes.EDIT}
        <Flatpickr options={mergedOptions}
                   bind:value/>
        <button class="btn btn-xs btn-default"
                on:click={onCancel}>
            <Icon name="times"/>
        </button>
    {/if}
</main>

// waltz-ng/client/react-cli/components/common/DatePicker.tsx
import React, {useCallback, useMemo, useState} from "react";
import Flatpickr from "react-flatpickr";
import "flatpickr/dist/themes/confetti.css";
import {Options} from "flatpickr/dist/types/options";
import styles from "./DatePicker.module.css";
// Assuming an Icon component exists in React with a similar API
import Icon from "./Icon";
import Button from "./button/Button";

const Modes = {
    VIEW: "VIEW",
    EDIT: "EDIT"
} as const;

type Mode = typeof Modes[keyof typeof Modes];

const formatDate = (d: Date): string => {
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
};

export interface DatePickerProps {
    origDate?: Date;
    options?: Partial<Options>;
    canEdit?: boolean;
    onChange?: (newDate: Date) => void;
    className?:string;
    inputClassName?:string;
}

const DatePicker: React.FC<DatePickerProps> = (
    {
        origDate = new Date(),
        options = {},
        canEdit = false,
        onChange,
        className,
    inputClassName
    }) => {

    const [mode, setMode] = useState<Mode>(Modes.VIEW);
    const [originalDate] = useState<Date>(() => new Date(origDate));
    const [value, setValue] = useState<Date>(() => new Date(originalDate));

    const handleSubmit = useCallback((newDate: Date) => {
        if (originalDate.getTime() !== newDate.getTime()) {
            onChange?.(newDate);
        }
    }, [onChange, originalDate]);

    const onCancel = useCallback(() => {
        setValue(new Date(originalDate));
        setMode(Modes.VIEW);
    }, [originalDate]);

    const onEdit = useCallback(() => {
        setMode(Modes.EDIT);
    }, []);

    const mergedOptions: Options = useMemo(() => {
        const defaultOptions: Options = {
            dateFormat: "Y-m-d",
            enableTime: false,
            allowInput: true,
            onChange: (dates) => {
                if (dates[0]) {
                    handleSubmit(dates[0]);
                    setMode(Modes.VIEW);
                }
            }
        };
        return {
            ...defaultOptions,
            ...options
        };
    }, [options, handleSubmit]);

    const formattedValue = useMemo(() => formatDate(value), [value]);

    return (
        <div className = {[styles.wrapper,className].filter(Boolean).join(" ")}>
            {mode === Modes.VIEW
                ? (
                    <>
                        <span className={styles.readonly}>{formattedValue}</span>
                        {canEdit && (
                            <Button className={styles.inlineBtn}
                                    label={<><Icon name="edit"/></>}
                                    onClick={onEdit}
                            />

                        )}
                    </>
                ) : (
                    <>
                        <Flatpickr
                            className={[styles.input,inputClassName].filter(Boolean).join(" ")}
                            options={mergedOptions} value={value} onChange={([d]: Date[]) => setValue(d)}/>
                        <Button className={styles.inlineBtn}
                                label={<><Icon name="times"/></>}
                                onClick={onCancel}
                        />
                    </>
                )}
        </div>
    );
};

export default DatePicker;
